### ISSUE TITLE
would you add more examples

### ISSUE THREAD

**Issue by GallonDeng** [reefactor/cppy3#1]
great work! There are plenty of awsome functions in the repo. It would be better to add more useful examples to show how to use these built-in functions to embed python in c/c++ in real application, such as how to import python module, access module method, access python class, use numpy to do math, etc. Thanks!

**Comment by GallonDeng** [comment]
also found a bug, in the cppy3.hpp, the declared function is "void appendToSysPath(const std::list<std::wstring>& paths)", but in the cppy3.cpp, the defined is ""void appendToSysPath(const std::vector<std::wstring>& paths)

**Comment by reefactor** [comment]
Thanks, appendToSysPath() is fixed in https://github.com/reefactor/cppy3/commit/7b54404143daea2de0195b1e3624535b695fd61a

Example contributed in https://github.com/reefactor/cppy3/pull/2

More examples are welcome
